### ISSUE TITLE
New cluster roadmap

### ISSUE THREAD

**Issue by daniviga** [gem/oq-infrastructure#11]
# New cluster deployment

## Preparation (3rd-4th week of October)

- [ ] Shrink GED4GEM
  - [ ] Check available space on Hope/Charles
  - [ ] Skip if enough space available
- [ ] Move stuff out of Hendrix
  - [x] Webservices
  - [x] Cloud
  - [x] GEM ECD - 171012
  - [ ] WEB Scarpati
- [ ] Backup stuff
  - [x] OQ Colombia
    - [x] Move to the P710 workstation temporarily?
  - [ ] Tiledev
  - [ ] windows7-dev
- [ ] Check

### Hendrix M915 upgrade 

- [ ] Install Ubuntu 16.04
  - [ ] LXC/LXD
  - [ ] KVM/libvirtd
- [ ] Restore services
  - [ ] windows7-dev
  - [ ] OQ Colombia
- [ ] Check

## New HW deployment  (1st week of November)
- [ ] ***Total poweroff*** (1-2 days)
  - [ ] Disassemble M1000e
  - [ ] Disassemble R720
  - [ ] Shutdown Eaton UPS
  - [ ] Move Eaton UPS bottom
  - [ ] Re-deploy M1000e
  - [x] Install 10Gbps module on M6220
  - [ ] Re-deploy M915
  - [ ] Install 10Gbps card on Wilson
  - [ ] Re-deploy R720
- [x] M630 deployment
- [ ] Check

## M630 setup (1st week of November)
- [x] Install Ubuntu 16.04
- [x] Compile Python 3.6
 - [x] Setup NFS
 - [x] Setup SSH + accounts
- [ ] Check

## Switch  (1st-2nd week of November)
- [ ] Switch main cluster to the new one
- [ ] Check

## M915 upgrade (2nd-3rd week of November)
- [ ] Install Ubuntu 16.04 (18.04 beta?)
- [ ] Compile Python 3.6
- [ ] Setup NFS
- [ ] Setup SSH + accounts

## ZMQ testing (TBD)
- [x] Attach Hendrix
- [ ] Run extensive ZMQ testing

## Old cluster deployment (TBD)
- [ ] Choose distribution mechanism
- [ ] Configure Wilson to work as a multi-cluster master
- [ ] Check

cc @micheles @pslh

**Comment by daniviga** [comment]
- [ ] Put RabbiMQ into docker container
